language: generic
sudo: required
services:
    - docker

# before_install:
#     - docker build -t bingani/react-test -f ./client/Dockerfile.dev ./client

script:
    - cd client
    - ls

# after_success:
#     - docker build -t bingani/multi-client ./client
#     - docker build -t bingani/multi-nginx ./nginx
#     - docker build -t bingani/multi-server ./server
#     - docker build -t bingani/multi-worker ./worker
#     # Log in to the docker CLI
#     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#     # Take those images and push them to docker hub
#     - docker push bingani/multi-client
#     - docker push bingani/multi-nginx 
#     - docker push bingani/multi-server
#     - docker push bingani/multi-worker